config/routes.rb
Rails.application.routes.draw do



  resources :groups do
    resources :posts do
      resources :replies
    end
  end

  resources :users
  resources :tags
  resources :dashboards, only: [:index]


  root 'groups#show', :id => 'community'
  get 'signin' => 'sessions#new'
  post 'postupload' => 'posts#upload_file'
  post 'replyupload' => 'replies#upload_file'
  get 'groupposts/:id', to: 'groups#groupposts', as: 'groupposts'
  resource :session

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :groupmembers, dependent: :destroy
  has_many :users, through: :groupmembers
  validates :name, presence: true

  before_save :generate_slug

  def to_param
    self.slug
  end

  def generate_slug
    self.slug ||= name.parameterize if name
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_signin
  before_action :require_admin, except: [:show]
  before_action :get_user
  before_action :get_tags
  before_action :current_group, only: [:edit, :update, :destroy, :show, :groupposts]
  before_action :get_all_users, only: [:edit, :new]
  before_action :get_allowed, only: [:show]

  def index
    @groups = Group.all.order(:name)
  end

  def show
    if @user.groups.find_by(id: @group.id)
      unless params[:tag].nil?
        @tag = Tag.find_by(name: params[:tag])
        session[:tag] = @tag.id
        @tagname = @tag.name
        @posts = @group.posts.order(updated_at: :desc).where(tag_id: @tag.id).includes(:tag).includes(:user).page(params[:page]).per_page(40)
      else
        @tagname = 'All'
        session[:tag] = nil
        @posts = @group.posts.order(updated_at: :desc).includes(:tag).includes(:user).page(params[:page]).per_page(40)
      end
      update_visit
    else
      redirect_to root_path, :gflash => { :notice => "Not authorized for group" }
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, :gflash => { :success => "Group created successfully" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    @group.slug = params[:name]
    if @group.update(group_params)
      redirect_to @group, :gflash => { :success => "Group updated!" }
    else
      render :edit
    end
  end

  def destroy
      @group.destroy
      redirect_to groups_path, :gflash => { :success => "Group deleted" }
  end

  def groupposts
    if @user.groups.find_by(:id=>@group.id)
      update_visit
      #@posts = @group.posts.text_search(params[:query]).includes(:tag).includes(:user).page(params[:page]).per_page(40)
      unless session[:tag].nil?
        #@tag = Tag.find(session[:tag])
        tagid=session[:tag]
        @posts = @group.posts.order(created_at: :desc).where(tag_id: tagid).includes(:tag).includes(:user).page(params[:page]).per_page(40)
      else
        @posts = @group.posts.order(created_at: :desc).includes(:tag).includes(:user).page(params[:page]).per_page(40)
      end
    end
  end




  private

  def get_all_users
    @users = User.all
  end

  def current_group
    @group = Group.find_by(slug: params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :slug, user_ids: [])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this Group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="row left">
  <div class="small-12 medium-8 columns">
    <%= f.label "Group Name", class: "bold" %><br>
    <%= f.text_field :name, class: "radius" %>
  </div>
</div>


<div class="row left">
  <div class="small-12 medium-8 columns">
    <%= f.collection_check_boxes(:user_ids, @users, :id, :name) do |b| %>
    <%= b.label { b.check_box + ' ' + b.text } %>
    <% end %>
  </div>
</div>





<div class="row left">
  <div class="small-12 columns">
    <%= f.submit "Save", class: 'button tiny radius' %>

<%end%>

app/views/groups/edit.html.erb
<div class="bodywrapper">
<h3 id='storyheader'>Editing group</h3>

<%= render 'form' %>

<%= link_to 'Cancel', groups_path, class: "button tiny radius" %>
</div>

app/views/groups/groupposts.js.erb
$("#groupposts").empty();
$('#groupposts').append("<%= j render partial: 'layouts/groupcontent' %>");

app/views/groups/index.html.erb
<div class="bodywrapper">
<h3 id='storyheader'>Listing groups</h3>



<table>
  <thead>
    <tr class="liner">
      <th>Name</th>

      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group %></td>
        <td> <%= link_to 'Edit', edit_group_path(group) %> |
         <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Group', new_group_path, class: "button tiny radius" %>

app/views/groups/new.html.erb
<div class="bodywrapper">
<h3 id="storyheader">New Group</h3>

<%= render 'form' %>




<%= link_to 'Cancel', dashboards_path, class: "button tiny radius" %>
</div>
</div>
</div>

app/views/groups/show.html.erb
<div class="bodywrapper">
<br>
<div id="groupposts" data-url="<%= groupposts_url(@group) %>">
  <%= render 'layouts/groupcontent' %>
</div>
<%= will_paginate @posts, previous_label: h("<"), next_label: h(">") %>
</div>

app/views/groups/show.js.erb
$('#postrows').append('<%= j render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>