config/routes.rb
Rails.application.routes.draw do



  resources :groups do
    resources :posts do
      resources :replies
    end
  end

  resources :users
  resources :tags
  resources :dashboards, only: [:index]


  root 'groups#show', :id => 'community'
  get 'signin' => 'sessions#new'
  post 'postupload' => 'posts#upload_file'
  post 'replyupload' => 'replies#upload_file'
  get 'groupposts/:id', to: 'groups#groupposts', as: 'groupposts'
  resource :session

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_attached_file :photo,
                    :styles => {
                      :thumb => ["80x80", :jpg],
                    },
                    :default_style => :thumb
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  has_many :posts
  has_many :replies
  has_many :groupmembers, dependent: :destroy
  has_many :groups, through: :groupmembers
  validates :name, presence: true
  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }
  def gravatar_id
  	Digest::MD5::hexdigest(email.downcase)
  end

  def self.authenticate(email, password)
  	user = User.find_by(email: email)
  	user && user.authenticate(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy, :index, :new, :create]
  before_action :get_user

def index
    @users = User.all
end

def new
  if current_user
    #redirect_to @user, :gflash => { :notice => "Already signed in" }
  end
	@user=User.new

end

def show
	@user = User.find(params[:id])
end

def create
  		@user = User.new(user_params)
  		if @user.save
		    #session[:user_id] = @user.id
    		redirect_to @user, :gflash => { :success => "Account Created" }
  		else
    		render :new
  		end
	end

	def edit
  		@user = User.find(params[:id])

	end

	def update
  	@user = User.find(params[:id])

		if @user.update(user_params)
    	redirect_to @user, :gflash => { :success => "Account updated!" }
  	else
    	render :edit
  	end
	end

	def destroy
  		@user = User.find(params[:id])
  		@user.destroy
  		session[:user_id] = nil
  		redirect_to root_url, :gflash => { :success => "Account deleted" }
	end

	private

	def user_params
  	  params.require(:user).permit(:name, :email, :password, :password_confirmation, :photo, feed_ids: [])
	end

	def require_correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image_for(user, options={})
    size = options[:size] || 80
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}?s=#{size}"
    image_tag(url, alt: user.name, class: :gravatar)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true }  do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this User from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="row left">
  <div class="small-12 columns">
    <%= f.label "User Name", class: "bold" %><br>
    <%= f.text_field :name, :size=>"50", class: "radius entry" %>
  </div>
</div>


<div class="row left">
  <div class="small-12 columns">
    <%= f.label "User Email", class: "bold" %><br>
    <%= f.text_field :email, class: "radius entry" %>
  </div>
</div>

<div class="row left">
  <div class="small-12 columns">
    <%= f.label "Password", class: "bold" %><br>
    <%= f.password_field :password, class: "radius entry" %>
  </div>
</div>

<div class="row left">
  <div class="small-12 columns">
    <%= f.label "Password Confirmation", class: "bold" %><br>
    <%= f.password_field :password_confirmation, class: "radius entry" %>
  </div>
</div>

<div class="row left">
  <div class="small-12 columns">
    <%= f.label "Profile Picture", class: "bold" %><br>
    <%= image_tag @user.photo.url, :class => "gravatar" %><br>
    <%= f.file_field :photo %>
  </div>
</div>


<div class="row left">
  <div class="small-12 columns">
  <% if @user.new_record? %>
    <%= f.submit "Create User", class: 'button tiny radius' %>
  <% else %>
    <%= f.submit "Update Account",  class: 'button tiny radius' %>
  <% end %>



<% end %>

app/views/users/edit.html.erb
<div class="bodywrapper">
<h3 id='storyheader'>Editing user</h3>

<%= render 'form' %>

<%= link_to 'Show', @user, class: "button tiny radius" %>
<%= link_to 'Back', users_path, class: "button tiny radius" %>
</div>

app/views/users/index.html.erb
<div class="bodywrapper">
<h3 id='storyheader'>Listing users</h3>



<table>
  <thead>
    <tr class="liner">
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td> <%= link_to 'Edit', edit_user_path(user) %> |
         <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New User', new_user_path, class: "button tiny radius" %>
</div>

app/views/users/new.html.erb
<div class="bodywrapper">
<h3 id='storyheader'>Sign Up</h3>

<%= render 'form' %>




<%= link_to 'Cancel', root_path, class: "button tiny radius" %>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="bodywrapper">
<br>

<p>
  <%= image_tag @user.photo.url, :class => "gravatar" %>
  <br>
  <strong>Name:</strong>
  <%= @user.name %><br>



  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: "button tiny radius" %>
<%= link_to 'Logout', logout_path, method: :delete, :class => "button tiny radius" %>
<% if current_user_admin? %>
  <%= link_to 'All Users', users_path, class: "button tiny radius" %>
<% end %>
</div>