config/routes.rb
Rails.application.routes.draw do



  resources :groups do
    resources :posts do
      resources :replies
    end
  end

  resources :users
  resources :tags
  resources :dashboards, only: [:index]


  root 'groups#show', :id => 'community'
  get 'signin' => 'sessions#new'
  post 'postupload' => 'posts#upload_file'
  post 'replyupload' => 'replies#upload_file'
  get 'groupposts/:id', to: 'groups#groupposts', as: 'groupposts'
  resource :session

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  belongs_to :tag
  has_many :replies, dependent: :destroy
  validates :title, presence: true, uniqueness: true
  validates :group_id, presence: true
  validates :tag_id, presence: true
  validates :user_id, presence: true
  validates_length_of :entry, :in => 2..10000, :allow_blank => false

  include PgSearch
  pg_search_scope :search, against: [:title, :entry],
  using: {tsearch: {dictionary: "english"}},
  associated_against: {replies: :entry}

  def self.text_search(query)
    if query.present?
      search(query)
    else
      order("created_at DESC")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :js, :html
  before_action :require_signin
  before_action :get_user
  before_action :get_group
  before_action :get_post, only: [:show, :edit, :update, :destroy ]
  before_action :get_allowed

  def new
    @post = Post.new
  end

  def show
    @replies = @post.replies.includes(:user).order(:created_at)
    @reply = Reply.new
  end

  def edit
  end

  def upload_file
    if params[:file]
      FileUtils::mkdir_p(Rails.root.join('public/uploads/files'))
      ext = File.extname(params[:file].original_filename)
      file_name = "#{SecureRandom.urlsafe_base64}#{ext}"
      path = Rails.root.join('public/uploads/files/', file_name)
      File.open(path, "wb") {|f| f.write(params[:file].read)}
      render :text => {:link => "/uploads/files/#{file_name}"}.to_json
    else
      render :text => {:link => nil}.to_json
    end
  end

  def index
    if @user.groups.find_by(:id=>@group.id)
      @posts = @group.posts.text_search(params[:query]).includes(:tag).includes(:user).page(params[:page]).per_page(40)
    else
      redirect_to root_path, :gflash => { :notice => "Not authorized for group" }
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.js {render :show}
      else
        format.js {render :edit}
      end
    end
  end

  def create
    @post = Post.new(post_params)
    @post.group_id = @group.id
    @post.user_id = @user.id
    if @post.save
      @group.users.each do |member|
        SendEmailJob.set(wait: 20.seconds).perform_later(@group, @post, member)
      end
      redirect_to group_path(@group), :gflash => { :success => "Posted successfully" }
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to group_path(@group), :gflash => { :success => "Post deleted" }
  end

  private

  def get_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :entry, :tag_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@group, @post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this Post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h3 id="storyheader">New Post</h3>

<div class="row left">
  <div class="small-12 medium-8 columns">
    <%= f.label "Title", class: "bold" %><br>
    <%= f.text_field :title, class: "radius" %>
  </div>
</div>

<div class="row left spacer">
  <div class="small-3 medium-2 columns">
    <%= f.collection_select(:tag_id, Tag.all.order(:name), :id, :name, :prompt => true ) %>
  </div>
</div>

<div class="row left spacer">
  <div class="small-12 medium-8 columns">
    <%= f.label "Entry", class: "bold" %><br>
    <hr class="linespace">
    <%= f.text_area :entry, :id => 'newreply' %>
  </div>
</div>



<div class="row left">
  <div class="small-12 columns">
    <%= f.submit "Create Post", class: 'button tiny radius' %>

<%end%>

<script>
  $(function() {
    $('textarea#newreply').froalaEditor({
      imageUploadURL: '/postupload',
      fileUploadURL: '/postupload',
      entities: '&#39;',
      requestHeaders: {
        'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
      },
      imageUploadParams: {
        id: 'my_editor'
      },
      placeholderText: 'Type something',
      toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'fontFamily', 'fontSize', 'color', 'formatParagraph', 'paragraphStyle', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'insertLink', 'insertImage', 'insertFile', 'insertVideo', 'insertTable', 'undo', 'redo', 'html', 'clearFormatting', 'fullscreen'],
    })
  });
</script>

app/views/posts/_formedit.html.erb
<%= form_for [@group, @post], remote:true do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this Post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label "Title", class: "bold" %><br>
    <%= f.text_field :title, class: "radius" %>


    <%= f.label "Tag", class: "bold" %><br>
    <%= f.collection_select(:tag_id, Tag.all.order(:name), :id, :name, :prompt => true ) %>



    <%= f.label "Entry", class: "bold" %><br>
    <hr class="linespace">
    <%= f.text_area :entry, :id => 'editreply' %>
<br>




    <%= f.submit "Edit Post", class: 'button tiny radius' %> <%= link_to 'Cancel', group_post_path(@group, @post), class: "button tiny radius", :remote => true %>

<%end%>

<script>
  $(function() {
    $('textarea#editreply').froalaEditor({
      imageUploadURL: '/postupload',
      entities: '&#39;',
      requestHeaders: {
        'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
      },
      imageUploadParams: {
        id: 'my_editor'
      },
      placeholderText: 'Type something',
      toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'fontFamily', 'fontSize', 'color', 'formatParagraph', 'paragraphStyle', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'insertLink', 'insertImage', 'insertVideo', 'insertTable', 'undo', 'redo', 'html', 'clearFormatting', 'fullscreen'],
    })
  });
</script>

app/views/posts/_post.html.erb
  <tr data-href= "<%= group_post_path(@group, post) %>">
    <td style="border-left: 5px solid rgb(255, 255, 255);" colspan="2"><%= post.title %></td>
    <td><%= time_ago_in_words(post.created_at) %> ago</td>
    <td><span class='<%= post.tag.color %> label radius'><%= post.tag.name %></span></td>
    <td><%= image_tag(post.user.photo.url, size: "25x25", :class => "gravatar") + ' ' + post.user.name %></td>
  </tr>

app/views/posts/_showheader.html.erb
<%= link_to @group.name, group_path(@group) %> / <%= @post.title %>

app/views/posts/_showpost.html.erb
<%= raw(@post.entry) %>

app/views/posts/_showposttag.html.erb
<%= @post.tag.name %>

app/views/posts/edit.js.erb
$("#postbody").empty();
$('#postbody').append("<%= j render partial: 'formedit' %>")

app/views/posts/index.html.erb
<div class="bodywrapper">
<br>

<%= render 'layouts/groupcontent' %>
</div>

app/views/posts/new.html.erb
<div class="bodywrapper">


<%= render 'form' %>




<%= link_to 'Cancel', group_path(@group), class: "button tiny radius" %>
</div>
</div>
</div>

app/views/posts/show.html.erb
<div class="bodywrapper">
<br>
<div class="head"></div>
<div class="row columns">
  <div class="small-12 columns">
    <h3 id="storyheader" style="float: left;"><%= link_to @group.name, group_path(@group) %> / <%= @post.title %></h3>
    &nbsp;<span id='posttag' class='<%= @post.tag.color %> label radius'><%= @post.tag.name %></span>
  </div>
</div>



<div class="row columns">
  <div class="small-12 columns ">


    <div class="avatar">
      <%= image_tag(@post.user.photo.url, size: "35x35", :class => "gravatar") %>
    </div>
    <div class="post-entry">
      <div class="post-header">
        <strong><%= @post.user.name %></strong><span class="time"><%= " " + time_ago_in_words(@post.created_at) + " ago" %></span>
        <!--<%= link_to '+   REPLY', new_group_post_reply_path(@group, @post), :class=>'button tiny radius right', 'data-no-turbolink' => true, remote: true %>-->
        <% if @post.user.name == @user.name %>
          <%= link_to "#{image_tag("pencil2.png", size: "20")}".html_safe, edit_group_post_path(@group, @post), :title => "Edit", remote: true %> <%= link_to "#{image_tag("cross.png", size: "15")}".html_safe, group_post_path(@group, @post), :title => "Delete", :title => "Delete", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
      <div class="post-body" id="postbody">
        <%= raw(@post.entry) %>
      </div>
    </div>
  </div>
</div>

<div id="replies_<%= @group.id %>_<%= @post.id %>" data-url="<%= group_post_replies_url(@group, @post) %>">

    <%= render 'replies/getit' %>

</div>

<div class="add-reply">
  <%= render "layouts/add_reply" %>
</div>

</div>

<script language="javascript">
  $(function() {
    if(typeof faye==="undefined"){
      var faye = new Faye.Client('<%= ENV['SERVER'] %>/faye');
    }
    if(typeof sub<%= @post.id %>==="undefined"){
      sub<%= @post.id %> = faye.subscribe('/replies/<%= @post.id %>', function (data) {
        eval(data);
      });
    }
  });
</script>

app/views/posts/show.js.erb
$("#postbody").empty();
$('#postbody').append("<%= j render partial: 'showpost' %>")
$("#storyheader").empty();
$('#storyheader').append("<%= j render partial: 'showheader' %>")
$("#posttag").empty();
$('#posttag').append("<%= j render partial: 'showposttag' %>")
$('#posttag').removeClass('alert default info secondary success warning').addClass('<%= @post.tag.color %>');
window.history.replaceState(null, null, "/groups/<%= @group.slug %>/posts/<%= @post.id %>");