config/routes.rb
Rails.application.routes.draw do



  resources :groups do
    resources :posts do
      resources :replies
    end
  end

  resources :users
  resources :tags
  resources :dashboards, only: [:index]


  root 'groups#show', :id => 'community'
  get 'signin' => 'sessions#new'
  post 'postupload' => 'posts#upload_file'
  post 'replyupload' => 'replies#upload_file'
  get 'groupposts/:id', to: 'groups#groupposts', as: 'groupposts'
  resource :session

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
end

app/views/layouts/_add_reply.html.erb
<div class="row columns">
  <div class="small-12 columns ">


    <div class="avatar">
      <%= image_tag(@user.photo.url, size: "35x35", :class => "gravatar") %>
    </div>
    <div class="post-entry">
      <div class="post-header">
        <strong>add comment</strong>
      </div>
      <div class="post-body" id="addreply">
        <%= form_for [@group, @post, @reply], remote:true do |f| %>
          <%= f.text_area :entry, :id => "newreply" %>
          <br>
          <%= f.submit "Reply", class: 'button tiny radius' %>
        <%end%>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('textarea#newreply').froalaEditor({
      imageUploadURL: '/replyupload',
      entities: '&#39;',
      requestHeaders: {
        'X-CSRF-Token': '<%= form_authenticity_token.to_s %>'
      },
      imageUploadParams: {
        id: 'my_editor'
      },
      placeholderText: 'Type something',
      toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'fontFamily', 'fontSize', 'color', 'formatParagraph', 'paragraphStyle', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'insertLink', 'insertImage', 'insertVideo', 'insertTable', 'undo', 'redo', 'html', 'clearFormatting', 'fullscreen'],
    })
  });
</script>

app/views/layouts/_groupcontent.html.erb
<div class="row columns">
  <div class="small-12 columns">
    <% if @posts %>
      <table id="postrows">
        <tbody id="posts">
          <% @posts.each do |post| %>
            <% cache([post, post.replies.count]) do %>
              <tr data-href= "<%= group_post_path(@group, post) %>">
                <% if post.replies.count > 0 %>
                  <td style="border-left: 5px solid rgb(255, 255, 255);" colspan="2"><%= post.title %><i class="fa fa-comments-o spacer-left" aria-hidden="true"></i><%= post.replies.count %></td>
                <% else %>
                  <td style="border-left: 5px solid rgb(255, 255, 255);" colspan="2"><%= post.title %></td>
                <% end %>
                <td><%= post.updated_at.strftime("%d %b %Y %k:%M") %> </td>
                <td><span class='<%= post.tag.color %> label radius'><%= post.tag.name %></span></td>
                <td><%= image_tag(post.user.photo.url, size: "25x25", :class => "gravatar") + ' ' + post.user.name %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/layouts/_groupnav.html.erb
<div class="row columns">
  <div class="small-4 medium-2 columns sizer">

    <a href="#" data-dropdown="drop1" class="button dropdown tiny radius"><%= @group.name %></a>
    <ul id="drop1" data-dropdown-content class="f-dropdown">
      <% @allowed.each do |group| %>
        <% unless @group.name == group.name %>
          <% cache do %>
            <li><%= link_to group.name, group %></li>
          <% end %>
        <% end %>
      <% end %>
    </ul>

</div>
<div class="small-5 medium-2 columns">
    <%= link_to '+   Post', new_group_post_path(@group), :class=>'button tiny radius' %>
</div>
<div class="medium-4 columns show-for-medium-up sizer2">
    <%= form_tag group_posts_path(@group), :method => 'get' do %>
      <%= text_field_tag :query, params[:query], class: "left inline textfield-size" %> <%= submit_tag "Search", :name => nil, class: "button tiny radius right" %>
   <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%= gflash nodom_wrap: true %>

app/views/layouts/_navigation.html.erb
<div class="sticky">
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1 class="shadow"><%= link_to "Core", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">


    <% unless controller.controller_name == "dashboards" || controller.controller_name == "users" || controller.controller_name == "tags" || controller.controller_name == "sessions" %>
      <% unless controller.controller_name == 'groups' && controller.action_name != "show" %>
          <ul class="left">
            <li><%= link_to '+   Post', new_group_post_path(@group), :class => 'small blue nice button src-download radius'%></li>
            <li>&nbsp;</li>
            <li class="has-dropdown">
              <a href="#"><%= @group.name %></a>
              <ul class="dropdown">
                <% @allowed.each do |group| %>
                  <% unless @group.name == group.name %>
                    <li><%= link_to group.name, group_path(group) %></li>
                  <% end %>
                <% end %>
              </ul>
            </li>
          </ul>

      <% end %>
    <% end %>

    <% if controller.controller_name == 'groups' && controller.action_name == "show" %>
          <ul class="left">
            <li>&nbsp;</li>
            <li class="has-dropdown">
              <a href="#"><%= @tagname %></a>
              <ul class="dropdown">
                <% unless @tagname == 'All' %>
                  <li><%= link_to 'All', group_path(@group) %></li>
                <% end %>
                <% @tags.each do |tag| %>
                  <% unless @tagname == tag.name %>
                    <li><%= link_to tag.name, group_path(@group, tag: tag.name) %></li>
                  <% end %>
                <% end %>
              </ul>
            </li>
          </ul>
    <% end %>







    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>
</div>

app/views/layouts/_navigation_links.html.erb
<!-- <li class="divider"></li> -->
<!-- <li class="divider"></li> -->
<% unless controller.controller_name == "dashboards" || controller.controller_name == "users" || controller.controller_name == "tags" || controller.controller_name == "sessions" %>
  <% unless controller.controller_name == 'groups' && controller.action_name != "show" %>
    <li class="shadow">
        <%= form_tag group_posts_path(@group), :class => 'searchform', :method => 'get' do %>
          <%= text_field_tag :query, params[:query], placeholder: "Search..." %>
        <% end %>
    </li>
  <% end %>
<% end %>
<% if current_user_admin? %>
  <li class="shadow"><%= link_to 'Dashboard', dashboards_path %></li>
<% end %>
<% if session[:user_id] %>
  <li class="shadow"><%= link_to image_tag(@current_user.photo.url, size: "35x35", :class => "gravatar") + ' ' + @current_user.name, @current_user %></li>
<% else %>
  <li class="shadow"><%= link_to 'Sign In', new_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= favicon_link_tag 'favicon.png' %>

    <title><%= content_for?(:title) ? yield(:title) : "Core" %></title>

    <%= stylesheet_link_tag    "application" %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "#{ENV['SERVER']}/faye.js" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= yield %>
    </main>

    <%= render 'layouts/messages' %>
    <a name="end"></a>
    <% if controller.controller_name == 'posts' && controller.action_name == 'show' %>

    <% end %>
  </body>
</html>

<script>
  $.FroalaEditor.DEFAULTS.key = '<%= ENV['FROALA_KEY'] %>';
</script>